const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_PAGE_INDEX = 1;
const DEFAULT_PAGE_SIZE_OPTIONS = [5, 10, 20, 50, 100];

export {
    DEFAULT_PAGE_SIZE,
    DEFAULT_PAGE_INDEX,
    DEFAULT_PAGE_SIZE_OPTIONS,
}